version = 1

test_patterns = [
    "**/*.test.ts",
    "**/*.test.tsx"
]

exclude_patterns = ["/assets/**"]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = [
    "nodejs",
    "browser",
    "jest"
  ]
  dialect = "typescript"
